apollo:
    bootstrap:
        eagerLoad:
            enabled: true
        enabled: true
    meta: http://127.0.0.1:8080
# apollo应用id
app:
    id: skyeye-application
mvc:
    throw-exception-if-no-handler-found: true
queue: skyeye
server:
    context-path: /
    port: ${server.port}
    tomcat:
        max-connections: 20000
        max-threads: 1000
        uri-encoding: utf-8
spring:
    activemq:
        broker-url: ${activite.path}
        in-memory: true
        password: ${activite.password}
        pool:
            enabled: false
            max-connections: 100
        user: ${activite.username}
    datasource:
        activiti:
            check-process-definitions: false
            driver-class-name: com.mysql.jdbc.Driver
            type: com.zaxxer.hikari.HikariDataSource
            jdbc-url: ${activiti.database.path}
            username: ${activiti.database.username}
            password: ${activiti.database.password}
        basedata:
            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
            driver-class-name: ${jdbc.database.driverClassName}
            initialSize: ${jdbc.initialSize}
            jdbc-url: ${jdbc.database.path}
            username: ${jdbc.database.username}
            password: ${jdbc.database.password}
            maxActive: ${jdbc.maxActive}
            maxPoolPreparedStatementPerConnectionSize: ${jdbc.maxPoolPreparedStatementPerConnectionSize}
            maxWait: ${jdbc.maxWait}
            minEvictableIdleTimeMillis: 30000
            minIdle: 6
            platform: mysql
            poolPreparedStatements: ${jdbc.poolPreparedStatements}
            testOnBorrow: false
            testOnReturn: false
            testWhileIdle: true
            timeBetweenEvictionRunsMillis: 60000
            type: com.zaxxer.hikari.HikariDataSource
            validationQuery: select 'x'
    # 热部署
    devtools:
        freemarker:
            cache: false
        restart:
            additional-paths: src/main/java
            enabled: true
            exclude: template/**
            log-condition-evaluation-delta: false
    transaction:
        rollback-on-commit-failure: true
    redis:
        isJq: false #是否开启集群 true：是 false：否

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql