server:
    servlet:
        context-path: /
    port: 8080
    tomcat:
        max-connections: 20000
        max-threads: 1000
        uri-encoding: utf-8
spring:
    banner:
        location: banner.txt
    resources:
        static-locations: classpath:/template/
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    # 热部署
    devtools:
        freemarker:
            cache: false
        restart:
            additional-paths: src/main/resources
            enabled: true
            log-condition-evaluation-delta: false